<?php
use Adeelq\ListInstalledModules\Block\Adminhtml\ListModulesBlock;
/** @var ListModulesBlock $block */
?>
<div class="admin__data-grid-wrap admin__data-grid-wrap-static">
    <table class="data-grid" id="adeelq-list-modules-table">
        <thead>
            <tr>
                <th class="data-grid-th">
                    <span>
                        <?= __('Module Name') ?>
                    </span>
                </th>
                <th class="data-grid-th">
                    <span>
                        <?= __('Version') ?>
                    </span>
                </th>
                <th class="data-grid-th">
                    <span>
                        <?= __('Module Dependencies') ?>
                    </span>
                </th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($block->getModulesList() as $module): ?>
                <tr>
                    <td>
                        <?= $module['name'] ?>
                    </td>
                    <td>
                        <?= $module['setup_version'] ?: __('Core Module') ?>
                    </td>
                    <td>
                        <?= implode('<br>', $module['sequence']) ?>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
